version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: knihovna
      POSTGRES_USER: knihovna
      POSTGRES_PASSWORD: heslo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knihovna"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: